name: ljbikes
description: A starting point for Dart libraries or applications.
version: 0.0.1+1

environment:
  sdk: '>=2.10.0 <3.0.0'

dependencies:
#  path: ^1.7.0

dev_dependencies:
  test: ^1.14.4
