name: ljbikes
description: A starting point for Dart libraries or applications.
version: 0.0.1+1

environment:
  sdk: '>=2.12.0-0 <3.0.0'

dependencies:
  http: ^0.12.2

dev_dependencies:
  test: ^1.16.0-nullsafety.13
